version: 2

models:
  - name: mart_genre_by_decade
    description: "Tabela agregada mostrando popularidade e notas médias de cada gênero ao longo das décadas."
    columns:
      - name: decade
        description: "A década de lançamento (ex: 1990, 2000, 2010)"
      - name: genre_name
        description: "O nome do gênero do filme"
      - name: total_movies
        description: "Quantidade de filmes lançados daquele gênero naquela década"
      - name: avg_rating
        description: "A nota média de todos os filmes daquele gênero na década"

  - name: mart_budget_over_time
    description: "Tabela agregada com os orçamentos médios por ano de lançamento."
    columns:
      - name: release_year
        tests:
          - unique
          - not_null
