version: 2

models:
  - name: stg_movies
    description: "Cleaned and typed movies data."
    columns:
      - name: movie_id
        tests:
          - unique
          - not_null
      - name: budget
      - name: revenue

  - name: stg_genres
    columns:
      - name: genre_id
        tests:
          - unique
          - not_null

  - name: stg_movie_genres
    columns:
      - name: movie_id
        tests:
          - not_null
      - name: genre_id
        tests:
          - not_null
