version: 2

models:
  - name: stg_movies
    description: "Cleaned and typed movies data."
    columns:
      - name: movie_id
        tests:
          - unique
          - not_null
      - name: budget
      - name: revenue

  - name: stg_genres
    columns:
      - name: genre_id
        tests:
          - unique
          - not_null

  - name: stg_movie_genres
    columns:
      - name: movie_id
        tests:
          - not_null

  - name: stg_credits_cast
    description: "Actors unnested from the credits JSON, with genders translated to EN."
    columns:
      - name: movie_id
        tests:
          - not_null

  - name: stg_credits_crew
    description: "Crew unnested, filtered exclusively for Directors."
    columns:
      - name: movie_id
        tests:
          - not_null

  - name: stg_movie_companies
    description: "Production companies and studios unnested."
    columns:
      - name: movie_id
        tests:
          - not_null

  - name: stg_movie_countries
    description: "Production countries unnested."
    columns:
      - name: movie_id
        tests:
          - not_null

  - name: stg_trending
    description: "Volatile data snapshot containing trending movies."
    columns:
      - name: movie_id
        tests:
          - not_null

  - name: stg_popular
    description: "Volatile data snapshot containing TMDB's most popular movies."
    columns:
      - name: movie_id
        tests:
          - not_null
